server:
  port: 8080
  servlet:
    context-path: /api
spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 2048MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: "password"
    url: jdbc:mysql://192.168.200.103:3306/speech_to_text?allowPublicKeyRetrieval=true&useSSL=false&useLegacyDatetimeCode=false
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
      
storage:
  location: 'C:/AUDIO_FILES/'


jwt:
  secret: $secret
  authorities: 
    key: role

paths:
  pythonTranscribeUrl: 'http://192.168.200.102:5000/transcribe'
  pythonGenerateDocumentUrl: 'http://192.168.200.102:5000/generate-document'

ffmpegPath: 'C:/ffmpeg.exe'



